openapi: '3.0.0'
info:
  title: 'Todo API'
  description: 'API для управления делами'
  version: '1.0.0'
servers:
  - url: 'http://localhost:8000'
paths:
  /todos:
    get:
      summary: 'Получить все дела'
      responses:
        200:
          description: 'Список дел'
    post:
      summary: 'Создать новое дело'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
      responses:
        201:
          description: 'Дело создано'
  /todos/{id}:
    get:
      summary: 'Получить дело по ID'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: 'Элемент дела'
        404:
          description: 'Дело не найдено'
    patch:
      summary: 'Обновить дело по ID'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                completed:
                  type: boolean
      responses:
        200:
          description: 'Дело обновлено'
        404:
          description: 'Дело не найдено'
    delete:
      summary: 'Удалить дело по ID'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: 'Дело удалено'
        404:
          description: 'Дело не найдено'