swagger: "2.0"
info: 
  version: "1.0.0"
  title: "Todo API"
  description: "A simple CRUD API for managing todos"
host: "localhost:8000"
basePath: "/"
schemes:
  - "http"
paths:
  /todos:
    get:
      summery: "Get all todos"
      responses: 
        200:
          description: "A list of todos"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Todo"
    post:
      summery: "Create a new todo"
      parameters:
        - name: "todo"
          in: "body"
          required: true
          schema:
          $ref: "#/definitions/Todo"
    responses:
      201:
        description: "Todo created"
        schema:
          $ref: "#/definitions/Todo"
  /todos/{id}:
    get:
      summary: "Get a todo by ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        200:
          description: "A todo item"
          schema:
            $ref: "#/definitions/Todo"
        404:
          description: "Todo not found"
    patch:
      summary: "Update a todo"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
        - name: "todo"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Todo"
      responses:
        200:
          description: "Updated todo"
          schema:
            $ref: "#/definitions/Todo"
        404:
          description: "Todo not found"
    delete:
      summary: "Delete a todo"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
      responses:
        204:
          description: "Todo deleted"
        404:
          description: "Todo not found"
definitions:
  Todo:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      completed:
        type: "boolean"
    required:
      - "title"